config/routes.rb
Rails.application.routes.draw do
 
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'  
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
 

  resources :users


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
# Above rule will produce help_path = '/help' and help_url = "localhost:3000/help"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
  	return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
    # Forgets a persistent session. 
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

  private

    def micropost_params
      params.require(:micropost).permit(:content)
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	 @micropost = current_user.microposts.build if logged_in?
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:edit, :update, :index, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def index
  	@users = User.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
      # Handle a successful update.
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
       # Before filters

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
      	store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    def correct_user
    	@user = User.find(params[:id])
    	redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
    	redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user?(user)
    user == current_user
  end

  # Returns the current logged-in user (if any).
  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

    # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
  	forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/layouts/_footer.html.haml
%footer{:class => 'footer'}
  %small
    The
    = link_to "Ruby on Rails Tutorial" ,"http://www.railstutorial.org/"
    to
    = link_to "Michael Hartl", "http://www.michaelhartl.com/"
  %nav
    %ul
      %li= link_to "About",   about_path 
      %li= link_to "Contact", contact_path
      %li= link_to "News", "http://news.railstutorial.org/"
  

app/views/layouts/_header.html.haml
%header{class: "navbar navbar-fixed-top navbar-inverse"}
	%div{class: "container"}
		= link_to("sample app", root_path , id: "logo")
		%nav
			%ul{class: "nav navbar-nav navbar-right"}
				%li= link_to("Home",   root_path)
				%li= link_to("Help",   help_path)
				- if logged_in?
					%li= link_to "Users", users_path
					%li{ class: "dropdown"}
						%a{href: '#', class: "dropdown-toggle", data:  {toggle:  "dropdown"}}
							Account
							%b{class:  "caret"}
						%ul{class: "dropdown-menu"}
							%li= link_to "Profile", current_user
							%li= link_to "Setting", edit_user_path(current_user)
							%li{class: "divider"}
							%li= link_to "Log out" , logout_path , method: :delete
				- else
					%li= link_to "Log in" , login_path

app/views/layouts/application.html.haml
%html
    %head
        %title= full_title(yield(:title))
        = csrf_meta_tags 
        = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' 
        = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
        = render 'layouts/shim'
    %body
        = render 'layouts/header'
        .container
            - flash.each do |message_type, message|
                %div{:class => "alert alert-#{message_type}"}
                    = message
            = yield
            = render 'layouts/footer'
            = debug(params) if Rails.env.development?

app/views/microposts/_micropost.html.haml
%li{id: "micropost-#{micropost.id}"}
	= link_to gravatar_for(micropost.user, size: 50), micropost.user
	%span{class: "user"}
	= link_to micropost.user.name, micropost.user
	%span{class: "content"}
	= micropost.content
	%span{class: "timestamp"}
		Posted
		= time_ago_in_words(micropost.created_at)
		ago.
		- if current_user? (micropost.user)
			= link_to "delete", micropost , method: :delete, data: {confirm: "are u sure?"}

app/views/shared/_error_messages.html.haml
- if object.errors.any? 
  #error_explanation
    .alert.alert-danger
      The form contains 
      = pluralize(object.errors.count, 'error')
    %ul
    - object.errors.full_messages.each do |msg| 
      %li= msg

app/views/shared/_micropost_form.html.haml
= form_for(@micropost) do |f| 
	= render 'shared/error_messages', object: f.object
	.field
		= f.text_area :content, placeholder: "Compose new micropost..."
	= f.submit "Post", class: "btn btn-primary"

app/views/shared/_user_info.html.haml
= link_to gravatar_for(current_user, size: 50), current_user
%h1
 = current_user.name
%span
 = link_to "view my profile", current_user
%span
 = pluralize(current_user.microposts.count, "micropost")

app/views/static_pages/about.html.haml
- content_for :title , "About"
%h1 about

app/views/static_pages/contact.html.haml
- content_for :title , "Contact"
%h1 Contact
%p Contact the Ruby on Rails Tutorial about the sample app at the
= link_to "Contact page" , "http://www.railstutorial.org/contact" 

app/views/static_pages/help.html.haml
- content_for :title , "Help"
%h1 help

app/views/static_pages/home.html.haml
- content_for :title , "Home"
- if logged_in?
	.row
		%aside{class: "col-md-4"}
			%section{class: "user_info"}
				= render 'shared/user_info'
			%section{class: "micropost_form"}
				= render 'shared/micropost_form'
- else
	%div{class: 'center jumbotron'}
		%h1 Welcome to the Sample App
		%h2 This is the home page for the
		= link_to "Ruby on Rails Tutorial", 'http://www.railstutorial.org/'
		sample application. 
		%br
		= link_to "Sign up now!", signup_path, :class => "btn btn-lg btn-primary"
		%br 
		%br
		= link_to image_tag("rails.png"), 'http://rubyonrails.org/'
	    
    

app/views/users/_user.html.haml
%li 
	= gravatar_for user, size: 50
	= link_to user.name, user
	- if current_user.admin? && !current_user?(user)
		= link_to "delete", user, method: :delete, data: {confirm: "are u sure?"}

app/views/users/edit.html.haml
- content_for :title , "Edit user"
%h1 Update your profile
.row
  .col-md-6.col-md-offset-3
    = form_for @user do |f| 
      = render 'shared/error_messages', object: f.object
      = f.label :name 
      = f.text_field :name, :class => 'form-control'

      = f.label :email 
      = f.email_field :email, :class => 'form-control' 
      %br
      = f.label :password 
      = f.password_field :password, :class => 'form-control'

      = f.label :password_confirmation, "Confirmation" 
      = f.password_field :password_confirmation, :class => 'form-control'

      = f.submit "Save changes", :class => "btn btn-primary"

    .gravatar_edit
      = gravatar_for @user 
      = link_to "change", "http://gravatar.com/emails", target: '_blank'


/ if any problem : = form_for(@user, url: signup_path) do |f|

app/views/users/index.html.haml
- content_for :title, "All users"
%h1 All users
= will_paginate
%ul{:class => "users"}
	- @users.each do |user|
		= render user
= will_paginate

app/views/users/new.html.haml
- content_for :title , "Sign up"
%h1 Sign up
%p This is the sign up page for the new user.
.row
  .col-md-6.col-md-offset-3
    = form_for @user do |f| 
      = render 'shared/error_messages', object: f.object
      = f.label :name 
      = f.text_field :name, :class => 'form-control'

      = f.label :email 
      = f.email_field :email, :class => 'form-control' 
      %br
      = f.label :password 
      = f.password_field :password, :class => 'form-control'

      = f.label :password_confirmation, "Confirmation" 
      = f.password_field :password_confirmation, :class => 'form-control'

      = f.submit "Create my account", :class => "btn btn-primary"


/ if any problem : = form_for(@user, url: signup_path) do |f|

app/views/users/show.html.haml
- content_for :title , @user.name
%div{:class => "row"}
 %aside{:class => "col-md-4"}
  %section{:class => "user_info"}
   %h1
    = gravatar_for @user
    = @user.name
 .col-md-8
  - if @user.microposts.any?
   %h3 
    microposts
    = @user.microposts.count
   %ol{class: "microposts"}
    = render @microposts
   = will_paginate @microposts

 